### ISSUE TITLE
various issues

### ISSUE THREAD

**Issue by echna** [echna/world-development-indicators#9]
Some of these are quick to fix others more major. For now I just collected a few in a single issue. Some might warrant their own.
1. set maximal plot plot-ranges x and y axis to make year to year changes comparable <- Find max value for all counries and year for x and y axis.
2. plot breaks in 2014 and 2015 and any time before 1995
3. z-axis should be a fixed number to make year to year changes comparable, but this may not work for indicators with larger changes over the year
4. speed up plotting. SQL queries seem to be the culprit. Possibly by save all the data for the specified indicators into temporary file at the beginning?
5. add functionality to select countries or groups of countries
6. add traces of spots moving
   7 add tool to choose indicators

**Comment by gindeleo** [comment]
1. you know why it breaks?
2. if we load in all the years in advance we can try finding a good normalization.
3. How about having a text file with all the indicator we want. we can hand pick them. then we load them all and save them into hdf5 which is probably quicker. It will check everytime if the indicators in the list are loaded and if not it will get them from the db. To change the indicator just change the .txt file. 
   Like this we can also share the tool easier or put it on a webpage without having to add a GB database we only need bits from.

**Comment by echna** [comment]
2.? I guess you meant item two? I haven't checked the data yet. I suspect there is some data of different format or such.
1. agree
2. yes an hdf5 might be quicker, but we would have to rewrite a bunch of code. Maybe making a separate smaller sql db is quick enough? What might slow it down right now is that the sql queries have to cross-check too many entries that are not relevant.

**Comment by echna** [comment]
All fixed or moved to Issue#23.
